version: '3.6'
services:

  postgres:
    image: postgres:11
    container_name: postgres
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    volumes:
      - ${POSTGRES_DATA_MNT:-/pg_data/data}:${PGDATA:-/var/lib/postgresql/data}
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-pgpassword}
      - PGDATA=${PGDATA:-/var/lib/postgresql/data}
      - POSTGRES_DB=orthanc

  orthanc:
    image: jodogne/orthanc-plugins:latest
    container_name: orthanc
    depends_on:
      - postgres
    restart: always
    ports:
      - ${ORTHANC_DICOM_PORT:-4242}:4242
      - ${ORTHANC_HTTP_PORT:-8042}:8042
    volumes:
      - sampledata:/sampledata
      - ${ORTHANC_DB:-./orthanc_db}:/var/lib/orthanc/db
      - ${ORTHANC_CONFIG:-./config/orthanc.json}:/etc/orthanc/orthanc.json:ro
    environment:
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-pgpassword}
      - PGDATA=${PGDATA:-/var/lib/postgresql/data}
      - POSTGRES_DB=orthanc

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - ${MONGO_PORT:-27017}:27017
    volumes:
      - ${MONGO_DATA:-./mongo_data}:/data/db

  viewer:
    image: ohif/viewer:latest
    container_name: viewer
    depends_on:
      - mongo
      - orthanc
    restart: always
    ports:
      - 3000:3000
    links:
      - mongo
    environment:
      - MONGO_URL=${MONGO_URL:-mongodb://mongo:27017/ohif}
    volumes:
      - ${VIEWER_CONFIG:-./config/viewer.json}:/app/app.json:ro

volumes:
  sampledata:
